### ISSUE TITLE
Time function on Realtime blocks Node from exiting

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#9] opened 2015-02-24 20:40 UTC
@paddybyers, please see https://github.com/ably/ably-js/commits/time-issue-example, and specifically [this commit](https://github.com/ably/ably-js/commit/f2103788488bcd572e682dccd13d6b0cf60007d3).  

In the example test, I can recreate the issue whereby the test suite does not exit under Node.js.  To test this, simply uncomment https://github.com/ably/ably-js/commit/f2103788488bcd572e682dccd13d6b0cf60007d3#diff-8e96d4a2d277fa48d367d76e19feade6R56 and run the following command:

`grunt nodeunit --test spec/realtime/client_lib_issue.test.js`

If you try the same thing with the REST time function it works, and it also works fine if you simply connect to Realtime and then close it.  The problem appears to currently be isolated to the time function.

If there is any way you could fix this soon I'd appreciate it as it is a bit of an issue whilst trying to migrate the test suite.

**Comment by mattheworiordan** [comment] 2015-02-24 20:54
BTW. I am not 100% certain this issue is isolated to the realtime time function.  I have been able to replicate it with the Rest time function too, although it seems to lock up far less frequently oddly.

**Comment by paddybyers** [comment] 2015-02-24 21:21
I haven't been able to reproduce any instance of it hanging with Rest.

**Comment by mattheworiordan** [comment] 2015-02-25 01:10
@paddybyers I could reproduce it only after numerous attempts.

**Comment by paddybyers** [comment] 2015-02-25 06:59
Whatever the reason is, I don't think it is anything to do with the library. It might be one of the HttpClient agents hanging around; sometimes those can hang around until a timeout occurs, after 60s say. But there are no timers, connections, or anything else in the Rest library that would cause it.

**Comment by paddybyers** [comment] 2015-03-09 18:15
I have pushed fixes for this; you need both realtime and ably-js to re-test.

**Comment by paddybyers** [comment] 2015-04-03 23:21
Resolved

**Closed by paddybyers** 2015-04-03 23:21 UTC
Labels: bug
