### ISSUE TITLE
ConnectionManager.sendImpl(): Unexpected exception in transport.send(): TypeError: Cannot read property 'send' of null

### ISSUE THREAD

**Issue by mattheworiordan** [ably/ably-js#270] opened 2016-05-10 20:35 UTC
A user has hit a runtime error in the JS library which should not happen even if the underlying transports fail.  Separately we are investigating the root cause of the transport failure, however this issue is about the realtime library not correctly handling the failure.

```
Ably: Request.onabort(): Request cancelled, errorEvent type was abort, current statusText is 
ably.min.js?_=1462617215292:81 Ably: CometTransport.sendItems(): on complete: err = {"message":"Request cancelled, errorEvent type was abort, current statusText is ","code":80000,"statusCode":400}
ably.min.js?_=1462617215292:81 Ably: Transport.onProtocolMessage(): error; connectionKey = 8e985!Z2pEuPu18QgOEl85-100328e985; err = {"message":"Request cancelled, errorEvent type was abort, current statusText is ","code":80000,"statusCode":400}
rest.ably.io/comet/8e985!Z2pEuPu18QgOEl85-100328e985/send?access_token=[REMOVED]&rnd=9733905395760611:1 POST https://rest.ably.io/comet/8e985!Z2pEuPu18QgOEl85-100328e985/send?access_to…[REMOVED]&rnd=9733905395760611 404 (Not Found)
ably.min.js?_=1462617215292:81 Ably: CometTransport.sendItems(): on complete: err = {"statusCode":404,"code":40400,"message":"Invalid transport id: 100328e985","serverId":"frontend.9aff.eu-central-1-A.i-1a59c8a6"}
ably.min.js?_=1462617215292:81 Ably: Transport.onProtocolMessage(): error; connectionKey = 8e985!Z2pEuPu18QgOEl85-100328e985; err = {"message":"Invalid transport id: 100328e985","code":40400,"statusCode":404,"serverId":"frontend.9aff.eu-central-1-A.i-1a59c8a6"}
chat:1081 function::convBinding();
ably.min.js?_=1462617215292:81 Ably: ConnectionManager.sendImpl(): Unexpected exception in transport.send(): TypeError: Cannot read property 'send' of null
    at b.sendImpl (http://cdn.ably.io/lib/ably.min.js?_=1462617215292:147:361)
    at b.send (http://cdn.ably.io/lib/ably.min.js?_=1462617215292:146:460)
    at f.sendMessage (http://cdn.ably.io/lib/ably.min.js?_=1462617215292:216:252)
    at f.attachImpl (http://cdn.ably.io/lib/ably.min.js?_=1462617215292:213:268)
    at f.checkPendingState (http://cdn.ably.io/lib/ably.min.js?_=1462617215292:223:472)
    at f.setPendingState (http://cdn.ably.io/lib/ably.min.js?_=1462617215292:223:146)
    at f.attach (http://cdn.ably.io/lib/ably.min.js?_=1462617215292:212:434)
    at f._publish (http://cdn.ably.io/lib/ably.min.js?_=1462617215292:211:492)
    at f.publish (http://cdn.ably.io/lib/ably.min.js?_=1462617215292:211:67)
    at Object.Messages.sendMessage (http://demo.aircargobook.com/js/acb.messages.js:296:16)
```

**Comment by SimonWoolf** [comment] 2016-05-17 14:04
`sendImpl` is entitled to assume that `this.activeProtocol` exists, since it's only called if `state.sendEvents` is true, which is only the case when in the `connected` state, which should imply the existence of an active protocol. So the underlying problem here is that we're in the `connected` state when `activeProtocol` is null.

Looking over the code I can spot a case where that might be violated, but I can't be sure that was what was the problem here. Would be nice to see a full log_micro trace / steps to reproduce, but I guess that's not practical if a customer spotted it. https://github.com/ably/ably-js/pull/274 is a blind fix, hopefully this'll solve it.

**Comment by SimonWoolf** [comment] 2016-06-22 14:33
Assumed fixed by https://github.com/ably/ably-js/pull/274

**Closed by SimonWoolf** 2016-06-22 14:33 UTC
Labels: bug, high priority
