### ISSUE TITLE
Errors in publish callbacks are lost.

### ISSUE THREAD

**Issue by CrowdHailer** [ably/ably-js#194] opened 2016-01-11 10:49 UTC
If code within a publish callback throws an error the library swallows that error without even a log message. e.g this code will fail.

```js
var channel // Connect start channel etc
function sendReset(){
  channel.publish("resetReadings", {}, function(err) {
    if(err) {
      window.console.warn("Unable to publish message; err = " + err.message);
    } else {
      window.console.info("Message successfully sent", message);
    }
  });
}
```

This function used to accept a parameter message but now does not. Therefore the error thrown was `ReferenceError: message is not defined`. This was a trivial fix but would've been quicker if the error had been shown to me.

**Comment by SimonWoolf** [comment] 2016-01-11 11:20
I'm afraid I can't reproduce -- above code results in `Ably: EventEmitter.emit(): Unexpected listener exception: ReferenceError: message is not defined` printed to the console, in both firefox and chrome.

What version of ably-js are you using? There was a fix Matt did about a month ago possibly relevant to this that made it into 0.8.10. (Latest release is 0.8.13)

**Comment by CrowdHailer** [comment] 2016-01-11 11:35
I'm using the minified version on the CDN which is 0.8.13

Just checked the behaviour again.
Currently I get nothing printed the first time it is called.
Second time onwards I get the Error message you are reporting.

**Comment by SimonWoolf** [comment] 2016-01-11 12:29
> Currently I get nothing printed the first time it is called.
> Second time onwards I get the Error message you are reporting.

That's very strange.

I still can't reproduce with 0.8.13. Would you mind making a jsbin that shows the problem? Start with https://jsbin.ably.io/ewiyoh/19, which seems to work for me (ie logs the exception to the console). Edit at https://jsbin.ably.io/ewiyoh/19/edit (then lock the revision and share it when you've got it failing). Thanks :)

**Comment by SimonWoolf** [comment] 2016-01-21 12:22
@CrowdHailer any update on this?

**Comment by CrowdHailer** [comment] 2016-01-27 11:40
hmm So I updated your JSbin with a version that showed this behaviour but cannot find it. I will try and set it up again.

If I remember it was a timing issue. Messages can be published before the connection is established. It is those queued messages which have there error information lost.

**Comment by CrowdHailer** [comment] 2016-01-27 11:57
This is the code that produces the odd behaviour in my browser. In JS bin I am unsure what is happening. I think it might be wrapping the console.log calls from the cdn imported ably library. 
https://jsbin.ably.io/ewiyoh/24/edit

**Comment by SimonWoolf** [comment] 2016-01-27 15:30
Ah, thanks, I see what you mean now.

OK, so publishes that happen before you're attached are all bundled up together and sent once you attach, and their callbacks are all fired at once by a multicaster thingy -- which was catching and discarding exceptions. Easy enough fix: https://github.com/ably/ably-js/pull/219

Thanks for the bug report and the jsbin :)

**Comment by SimonWoolf** [comment] 2016-06-24 17:22
This was fixed by https://github.com/ably/ably-js/issues/219

**Closed by SimonWoolf** 2016-06-24 17:22 UTC
