### ISSUE TITLE
Issue in Presence with Mobile datapack 

### ISSUE THREAD

**Issue by Dhyey** [ably/ably-js#489] opened 2018-03-17 16:04 UTC
When ably js lib is open in mobile through mobile data. I read presence list from another device. and then I turn off mobile data in the first, now I read the presence, it does not remove it in the 30 sec time. I have seen it not being removed even for 12 min. 

However when you use wifi instead mobile data, it will remove from presence within 30 sec.

**Comment by funkyboy** [comment] 2018-03-19 09:12
@Dhyey I am trying to wrap my head around the scenario you posted. So:

- device1 has ably-js running and is connected via 3G
- device2 has ably-js running and is connected via 3G
- you turn off 3G in device1 (is WiFi on or off?)
- device2 (still connected only via 3G?) doesn't show that (user on) device1 is not online anymore

Is this correct?

Also, can you please share the code you are using to detect presence?
Maybe it's relevant, maybe not. Which devices are you testing this on? Android? iOS?

**Comment by Dhyey** [comment] 2018-03-20 08:57
Hi @funkyboy I am running two html files one in an android device (client.html) and second one in macbook pro(dashboard.html)

1) with ably on client.html, the client enters the presence of a channel.
2) dashboard.html, it gets memebers list and also hooks on update event
3) dashboard.html is successfully show client.html is online

This is working successfully in whether the android device is connected on internet by wifi or by 4G data. However, when the client.html is entering presence via wifi, and we turn wifi off, after 30 sec of time dashboard gets update from presence and shows that client.html is out of list. However, when client.html enters presence while 4G data is on, and we turn the mobile data off, dashboard.html gets no update event even after 12-13 min. Also, when I try to manually get members list from presence, client.html is still shown online even after a long time. 

I tested this in chrome browser in both the devices. I did this with motorola g5 and one plus 5 both. I am able to repeat this result every-time.

**Comment by funkyboy** [comment] 2018-03-20 09:37
@Dhyey thanks for your detailed report. One silly question:

> when client.html enters presence while 4G data is on, and we turn the mobile data off,

when you turn mobile data off, is the device connecting via WiFi? Or is it totally offline?

**Comment by Dhyey** [comment] 2018-03-20 15:32
when I mean turn mobile data off, I mean totally offline. The expected behaviour is the offline client will be removed from presence after 30 sec by default. This does not happen in case of 4G data. I tested with 3G too. It doesn't happen in 3G too.

**Comment by funkyboy** [comment] 2018-03-20 15:45
Thanks @dhyey

Which version of ably-js are you using?

Can you please send me the html file that you are using to reproduce this? No need to include the api key.

**Comment by Dhyey** [comment] 2018-03-21 07:48
I am using 1.0.13

I am attaching two files:
[htmls.zip](https://github.com/ably/ably-js/files/1832378/htmls.zip)

**Comment by funkyboy** [comment] 2018-03-21 08:47
@Dhyey thanks. Will investigate and let you know.

**Comment by funkyboy** [comment] 2018-03-21 17:53
@Dhyey I have set up a demo:

- [Dashboard](https://intense-beach-29047.herokuapp.com/dashboard.php)
- [Client](https://intense-beach-29047.herokuapp.com/)

While I am trying to reproduce it, please let me know that you can still reproduce it using the links above.

**Comment by Dhyey** [comment] 2018-03-22 06:29
@funkyboy yes, I tested again from your deployments, it is in fact being reproduced, didn't leave the presence after going offline for at least 15 min I waited.

**Comment by paddybyers** [comment] 2018-03-22 07:46
@Dhyey are you connected right now?

**Comment by Dhyey** [comment] 2018-03-22 09:58
No I wasn't. 
BTW on this deployment strangely I am also facing this issue by being online on wifi and turning it off. In short, the issue arises whenever you go offline in any way.

**Comment by funkyboy** [comment] 2018-03-22 10:00
@Dhyey we need to coordinate a live test for this. 
Can you please get in touch with me? cesare@ably.io

**Comment by funkyboy** [comment] 2018-03-23 10:19
Did some live testing with @Dhyey. First we tried [my deployment](https://intense-beach-29047.herokuapp.com/) and then his, using his own api key. We were not able to reproduce this.

**Comment by funkyboy** [comment] 2018-03-23 13:27
@Dhyey update from our backend team. Some new code was deployed yesterday and today. While it was not related to this issue, the deployment might have "cleaned up" the system, including the part that was triggering the misbehaviour that you reported. 
Let's keep this issue open, just in case you can reproduce it again in the next days.

**Comment by funkyboy** [comment] 2018-06-15 16:30
@Dhyey closing this. Feel free to reopen if you think it's still an issue. Thanks.

**Closed by funkyboy** 2018-06-15 16:30 UTC
Labels: investigate
