### ISSUE TITLE
Compilation Failure with Ably on Next.js --turbo

### ISSUE THREAD

**Issue by Elmosh** [ably/ably-js#1699] opened 2024-03-18 14:30 UTC
I've been integrating Ably with a Next.js application and encountered a lot of development warnings initially, which escalated to a compilation error when using Next.js turbo. This issue persists regardless of the package manager used; switching from pnpm to npm did not resolve the problem.

Given that Turbo is achieving a [99% pass rate](https://areweturboyet.com
) on next dev tests, it seems likely that Ably might soon face compatibility issues with a significant portion of Next.js projects if this issue remains unaddressed.

**Error Details:**
When attempting to compile, i get this error:

```
Failed to compile
./node_modules/keyv/src/index.js:22:14
Module not found
  20 | 	if (options.adapter || options.uri) {
  21 | 		const adapter = options.adapter || /^[^:+]*/.exec(options.uri)[0];
> 22 | 		return new (require(adapters[adapter]))(options);
     | 		            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  23 | 	}
  24 |
  25 | 	return new Map();

```

**Attempted Resolutions:**

* Switching between pnpm and npm as the package manager.
* Ensuring that the latest versions of all related packages are in use.
* Ignoring or Overrides didn't fix the errors: 

```
config.ignoreWarnings = [{ module: /node_modules\/keyv\/src\/index\.js/ }];
```

```
"overrides": {
    "cacheable-request": {
      "keyv": "npm:@keyvhq/core@~1.6.6"
    }
  }
```

* Uninstalling Ably fixes the errors.

I am reaching out for guidance on resolving this issue or to report it in case it's not already on your radar. Any advice on potential workarounds or fixes would be greatly appreciated, as the inability to use --turbo significantly impacts our development process.

┆Issue is synchronized with this [Jira Task](https://ably.atlassian.net/browse/ECO-4701) by [Unito](https://www.unito.io)

**Comment by VeskeR** [comment] 2024-03-27 12:56
Hello @Elmosh , sorry for the late reply. Thank you for bringing our attention to this issue!

I was able to reproduce the issue locally when using turbopack with npm/pnpm, specifically when using next.js App Router (not Pages). I was able to fix the issue with adding `ably` to the list of next.js `serverComponentsExternalPackages` in `next.config.js` (read more [here](https://nextjs.org/docs/app/api-reference/next-config-js/serverComponentsExternalPackages)):
```javascript
const nextConfig = {
  // ...
  experimental: {
    serverComponentsExternalPackages: ['ably'],
  },
};
```

This workaround fixes the issue both for npm/pnpm when using turbopack in App Router.
It also appears that you no longer need to have `overrides` field in `package.json`:
```json
"overrides": {
  "cacheable-request": {
    "keyv": "npm:@keyvhq/core@~1.6.6"
  }
}
```

as the option above also fixes `Critical dependency: the request of a dependency is an expression` warnings.

Let me know if this works for you!
___

The issue is coming from the fact that when using App Router specifically (not Pages, this issue is not reproducible when using Pages) dependencies used inside Server Components and Route Handlers will automatically be bundled by Next.js. This causes issues with some packages, usually the ones that have complex `require` statements, for example, requiring some packages dynamically during runtime. `keyv` is one of those packages as it has the next `require` statement when requiring its adapters ([code in repo](https://github.com/jaredwray/keyv/blob/main/packages/keyv/src/index.ts#L102)):
```javascript
return new (require(adapters[adapter]))(options);
```

And unfortunately `keyv` ends up being one of our upstream dependencies for node.js bundle, due to us using `got`: `got` -> `cacheable-request` -> `keyv`.

Using `serverComponentsExternalPackages` opt-outs from using Next.js bundling for specific packages and uses native Node.js `require` instead.
This is a common problem in App Router for a number of packages (for example, see next.js issue https://github.com/vercel/next.js/issues/52876), and using `serverComponentsExternalPackages` is the recommended approach here.

We will explore the possibility of removing the `got` dependency from our Node.js bundle to prevent issues like this one in the future, and not require you adding `ably` to the `serverComponentsExternalPackages` list. However, I cannot guarantee when or if this will occur.

**Comment by Elmosh** [comment] 2024-03-27 14:04
Hey @VeskeR, thank you for investigating the issue and providing a solution. I'm working on a large codebase, and I can confirm that this fix resolves the issue without causing any further complications. Additionally, removing `got` dependency would be beneficial.

**Comment by VeskeR** [comment] 2024-03-27 14:26
Thank you for confirmation @Elmosh , closing as resolved now. Will create a separate issue for exploring the possibility of removing the `got` dependency.

**Closed by VeskeR** 2024-03-27 14:26 UTC

**Comment by harrisrobin** [comment] 2024-10-08 19:17
For anyone who's here as well, I've also had to add @ably/chat to "serverComponentsExternalPackages" as it was also impacted by this issue.
