### ISSUE TITLE
DefinitelyTyped

### ISSUE THREAD

**Issue by funkyboy** [ably/ably-js#461] opened 2018-02-06 15:37 UTC
Not clear if we should make a PR to https://github.com/DefinitelyTyped anymore or if they changed process. I replied to the PR here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/22860

**Comment by funkyboy** [comment] 2018-02-06 15:37
cc @SimonWoolf @mattheworiordan

**Comment by funkyboy** [comment] 2018-02-06 15:39
BTW a search for "ably" [here](https://microsoft.github.io/TypeSearch/) leads to https://www.npmjs.com/package/@types/ably

**Comment by SimonWoolf** [comment] 2018-02-06 15:48
> BTW a search for "ably" here leads to https://www.npmjs.com/package/@types/ably

yes, those are the types from definitelytyped. See https://github.com/DefinitelyTyped/DefinitelyTyped#npm

> Not clear if we should make a PR to https://github.com/DefinitelyTyped anymore or if they changed process.

As you pointed out in slack, they're pretty clear in the readme: `If you are the library author, or can make a pull request to the library, bundle types instead of publishing to DefinitelyTyped.` - https://github.com/DefinitelyTyped/DefinitelyTyped#create-a-new-package . So we don't need to duplicate our types there. Only action is for you to maybe try out ably in a sample typescript project and make sure the way we bundle types works for typescript users, per slack discussion.

**Comment by funkyboy** [comment] 2018-02-14 06:52
Update: see project by @withakay https://github.com/withakay/ably-ts-hack

**Comment by withakay** [comment] 2018-02-14 09:15
I should point out that that above linked project was borne out of a desire to be able to create a `Message` instance from TypeScript. To this end, a modified ably.d.ts type definition file has been created. Consider it an experiment, it probably has flaws and can almost certainly be improved upon.

**Comment by mattheworiordan** [comment] 2018-02-14 09:50
> Update: see project by @withakay https://github.com/withakay/ably-ts-hack

@funkyboy what's the context of that?

I don't really follow what the issue is to be honest.  As far as I can tell from what @SimonWoolf  has stated, the types will be inferred in the bundled package automatically.  Where are you up to at this point and how is @withakay's TS relevant?

**Comment by funkyboy** [comment] 2018-02-14 10:04
@mattheworiordan current [types in ably-js](https://github.com/ably/ably-js/blob/master/ably.d.ts) allow writing something like 
```
let message = new Ably.ablyLib.Message();
message.name = 'ciao';
channel.publish(message);
```

which:

- throws a runtime exception (still investigating [here](https://github.com/funkyboy/ts))
- doesn't feel "natural"

@withakay volunteered to take a stab at types. I still have to check it, but this should allow writing:
```
let m = new Ably.Realtime.Message()
```
which I think better matches our JS hierarchy of classes (and documentation).

I am aware it's a breaking change for TS developers, hence still under investigation.

**Comment by mattheworiordan** [comment] 2018-02-14 10:06
Ok, thanks for the context.  I agree, `Ably.ablyLib.Message` is definitely not right :(

**Comment by funkyboy** [comment] 2018-02-22 17:28
Some progress here. 

Now `Message` is easier to import and use: https://github.com/funkyboy/ts/blob/master/src/index.ts#L29 

`ClientOptions` is a now class: https://github.com/funkyboy/ts/blob/master/src/index.ts#L10 
but just with few properties for testing. 

Related ongoing PR to make it a class is here: https://github.com/ably/ably-js/pull/475

**Comment by funkyboy** [comment] 2018-02-26 19:51
More progress.
Now `ClientOptions` exposes all the properties defined in the spec.

**Closed** 2018-04-04 11:12 UTC
Labels: investigate
