### ISSUE TITLE
Add more browser tests

### ISSUE THREAD

**Issue by funkyboy** [ably/ably-js#493] opened 2018-03-26 09:29 UTC
Following [this discussion about supported platforms](https://github.com/ably/ably-js/pull/481) let's add more browser tests. The idea is to add older browser versions so we can state which platforms we support with more confidence. Here's a list of candidates:

- [ ] Opera latest
- [ ] Firefox 51
- [ ] Chrome 56
- [ ] Opera 41

cc @SimonWoolf @paddybyers

┆Issue is synchronized with this [Jira Story](https://ably.atlassian.net/browse/SDK-298) by [Unito](https://www.unito.io/learn-more)

**Comment by SimonWoolf** [comment] 2018-03-26 10:38
> The idea is to add older browser versions so we can state which platforms we support with more confidence

Happy to add more platforms if that'd be useful. But to reiterate what I said in the other issue: the set of platform/browser combinations we support will always be vastly more than the set we can possibly test; we shouldn't conflate the two.

Also though -- a failure of `ci-travis-all` is currently useless as an indication of a regression for a PR, since it always fails due to the compatibility bugs we currently have. So spending time refining the exact versions of chrome it tests is really a bit pointless. Lets get it reliably passing first so it's actually useful -- i.e. fix all the bugs it currently exposes -- then we can start thinking about adding more platforms to it...

**Comment by funkyboy** [comment] 2018-03-26 19:41
@SimonWoolf I agree we should fix current failing tests before adding more browsers. See [this discussion for more details](https://github.com/ably/wiki/issues/280)

**Comment by owenpearson** [comment] 2021-10-12 13:33
Closing this as our browser testing setup has moved on quite a bit since this discussion and I'm pretty happy with the range of browsers we currently test on.

**Closed by owenpearson** 2021-10-12 13:33 UTC
Labels: enhancement
